/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateStockFundamentalArgs } from "./CreateStockFundamentalArgs";
import { UpdateStockFundamentalArgs } from "./UpdateStockFundamentalArgs";
import { DeleteStockFundamentalArgs } from "./DeleteStockFundamentalArgs";
import { StockFundamentalCountArgs } from "./StockFundamentalCountArgs";
import { StockFundamentalFindManyArgs } from "./StockFundamentalFindManyArgs";
import { StockFundamentalFindUniqueArgs } from "./StockFundamentalFindUniqueArgs";
import { StockFundamental } from "./StockFundamental";
import { StockFundamentalService } from "../stockFundamental.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => StockFundamental)
export class StockFundamentalResolverBase {
  constructor(
    protected readonly service: StockFundamentalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "StockFundamental",
    action: "read",
    possession: "any",
  })
  async _stockFundamentalsMeta(
    @graphql.Args() args: StockFundamentalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [StockFundamental])
  @nestAccessControl.UseRoles({
    resource: "StockFundamental",
    action: "read",
    possession: "any",
  })
  async stockFundamentals(
    @graphql.Args() args: StockFundamentalFindManyArgs
  ): Promise<StockFundamental[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => StockFundamental, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "StockFundamental",
    action: "read",
    possession: "own",
  })
  async stockFundamental(
    @graphql.Args() args: StockFundamentalFindUniqueArgs
  ): Promise<StockFundamental | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => StockFundamental)
  @nestAccessControl.UseRoles({
    resource: "StockFundamental",
    action: "create",
    possession: "any",
  })
  async createStockFundamental(
    @graphql.Args() args: CreateStockFundamentalArgs
  ): Promise<StockFundamental> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => StockFundamental)
  @nestAccessControl.UseRoles({
    resource: "StockFundamental",
    action: "update",
    possession: "any",
  })
  async updateStockFundamental(
    @graphql.Args() args: UpdateStockFundamentalArgs
  ): Promise<StockFundamental | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => StockFundamental)
  @nestAccessControl.UseRoles({
    resource: "StockFundamental",
    action: "delete",
    possession: "any",
  })
  async deleteStockFundamental(
    @graphql.Args() args: DeleteStockFundamentalArgs
  ): Promise<StockFundamental | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
