export type StockFundamentalUpdateInput = {
  c5y?: number;
  cotacao?: number;
  divbpatr?: number;
  dy?: number;
  evebit?: number;
  evebitda?: number;
  liq2m?: number;
  liqc?: number;
  mrgebit?: number;
  mrgliq?: number;
  pa?: number;
  pacl?: number;
  papel?: string | null;
  patrliq?: number;
  pcg?: number;
  pebit?: number;
  pl?: number;
  psr?: number;
  pvp?: number;
  roe?: number;
  roic?: number;
};
